### ISSUE TITLE
Unexpected identifier issue

### ISSUE THREAD

**Issue by etionsun** [koahubjs/koahub-simple-cms#1]
Flow the steps and occured below issue:

```
../NodeProjects/koahub-simple-cms/node_modules/koahub/app/lib/controller.class.js:124
    async action(path, ...args) {
          ^^^^^^
SyntaxError: Unexpected identifier
```

**Comment by einsqing** [comment]
Did you use eslint?

**Comment by etionsun** [comment]
No, it is compiling issue.
My operation is only performed clone,npm install and npm start.
Any solution about it?

**Comment by einsqing** [comment]
What operating system?Nodejs version?

**Comment by einsqing** [comment]
koahub.js 目前版本最低要求是7.6.0，报错应该是因为这个问题。
