### ISSUE TITLE
yarn装的依赖，启动没问题，但localhost:3000报错

### ISSUE THREAD

**Issue by atjiu** [koahubjs/koahub-simple-cms#3]
![](http://ww2.sinaimg.cn/large/ce56395agy1ffg0qns7kuj21kw0onwym.jpg)

**Comment by einsqing** [comment]
修复代码没？

**Comment by atjiu** [comment]
@einsqing 没，好像是this.session的问题，好多地方都用到这个了，我就没弄了

**Comment by einsqing** [comment]
你直接npm start启动，不要用nodemon，node版本是多少？

**Comment by atjiu** [comment]
@einsqing 一样的，node版是7.8
