### ISSUE TITLE
演示程序数据库访问出错，配置文件错误

### ISSUE THREAD

**Issue by zengqingsong** [koahubjs/koahub-simple-cms#4]
数据库的配置文件错误导致无法连接数据库，阅读框架的源码，修改如下：	
// 'koahub-mysql': {
	//     // "type": "mysql",
	//     "host": "127.0.0.1",
	//     "user": "koahub",
	//     "password": "koahub",
	//     "database": "koahub",
	//     "charset": "utf8"
	// },
	'koahub-mysql': {
		// "type": "mysql",
		connection: {
			host: 'localhost',
			user: 'koahub',
			password: 'koahub',
			database: 'koahub',
			charset: 'utf8'
		}
	},

另外这个框架吸收了TP的精华，希望能够将模板按照模块分目录组织，而不是一个模块所有的模板放在一个目录下。TP3.2以后的版本都是分目录组织的。

**Comment by einsqing** [comment]
@zengqingsong koahub-mysql 升级了，这个项目还没有更新。感谢您的建议

**Comment by zengqingsong** [comment]
增加一个koahub-mongo插件，用于访问mongo数据库，你测试一下可以放到仓库里。
曾青松


pypzengqs@126.com
 
发件人： einsqing
发送时间： 2018-01-15 11:11
收件人： koahubjs/koahub-simple-cms
抄送： zengqingsong; Mention
主题： Re: [koahubjs/koahub-simple-cms] 演示程序数据库访问出错，配置文件错误 (#4)
@zengqingsong koahub-mysql 升级了，这个项目还没有更新。感谢您的建议
